name: Transcribe Audio
on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'Audio Direct Link (သို့မဟုတ် YouTube Link)'
        required: true

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Speech to Text
        uses: appleboy/whisper-action@v0.1.1
        with:
          model: small
          youtube_url: ${{ github.event.inputs.audio_url }}
          output_format: srt
          output_folder: output
      - name: Upload SRT
        uses: actions/upload-artifact@v3
        with:
          name: subtitle
          path: output/
