name: Transcribe Audio
on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'တင်ထားသော audio ဖိုင်နာမည် (ဥပမာ - test.mp3)'
        required: true

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Speech to Text
        uses: appleboy/whisper-action@v0.1.1
        with:
          model: small
          audio_path: ${{ github.event.inputs.file_name }}
          output_format: srt
          output_folder: output
      - name: Upload SRT
        uses: actions/upload-artifact@v4
        with:
          name: subtitle
          path: output/
